version: "3.7"

networks:
    {{cookiecutter.project_slug.lower()}}_network:
      name: {{cookiecutter.project_slug.lower()}}_network

services:
  database_{{cookiecutter.project_slug.lower()}}:
    container_name: {{cookiecutter.project_slug.lower()}}_database
    image: postgres:14.3
    restart: always
    volumes:
      - {{cookiecutter.project_slug.lower()}}_db:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB={{cookiecutter.project_slug.lower()}}_db
      - POSTGRES_USER={{cookiecutter.project_slug.lower()}}_dbmanager_2LiyBoLHeHo5yG
      - POSTGRES_PASSWORD=2LiyBoLHeHo5yGfxan8euHGIzEEzIs
      - POSTGRES_HOST_AUTH_METHOD=md5
    networks:
      - {{cookiecutter.project_slug.lower()}}_network
    ports:
      - "{{cookiecutter.postgre_port}}:5432"

  django_{{cookiecutter.project_slug.lower()}}:
    container_name: {{cookiecutter.project_slug.lower()}}_django
    image: {{cookiecutter.project_slug.lower()}}:1.0
    platform: linux/amd64
    environment:
      - DB_NAME={{cookiecutter.project_slug.lower()}}_db
      - DB_HOST={{cookiecutter.project_slug.lower()}}_database
      - DB_PASSWORD=2LiyBoLHeHo5yGfxan8euHGIzEEzIs
      - DB_ENGINE=django.db.backends.postgresql
      - DB_USER={{cookiecutter.project_slug.lower()}}_dbmanager_2LiyBoLHeHo5yG
      - DB_PORT=5432
      - SECRET_KEY=NYPmGeU11uQ96YQtX9UjOZ_EuAGsuJltGJt5XBrXt0HQhgShCP7KIWlLFgxtZDhl0z4
      - ALLOWED_HOSTS=.localhost,*
      - DEBUG=True
      - SENTRY_DNS=""
      - API_PATH=http://localhost:8080/
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - EMAIL_PASSWORD=''
      - EMAIL_LOGIN=''
      - EMAIL_SMTP=''
      - EMAIL_PORTA=''
      - EMAIL_DESTINO=''
      - FCM_KEY=''
      - GOOGLE_API_KEY=''
      - HORAS_SEM_ATENDIMENTO=19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 12
      - DIAS_DA_SEMANA=0, 1, 2, 3, 4
      - SENHA_PADRAO=123456
      - CSRF_TRUSTED_ORIGINS=https://*.localhost,
    build:
      context: .
      dockerfile: ./DockerfileDev
    networks:
      - {{cookiecutter.project_slug.lower()}}_network
    command: bash -c "python manage.py collectstatic; python manage.py runserver 0.0.0.0:8000;"
    volumes:
      - .:/app
      - ../../FastAPI/{{cookiecutter.project_slug.lower()}}:/FastAPI
    ports:
      - "{{cookiecutter.docker_port}}:8000"
    depends_on:
      - database_{{cookiecutter.project_slug.lower()}}

volumes:
    {{cookiecutter.project_slug.lower()}}_db:

