[tool.taskipy.settings]
user_vars = true

[tool.pytest.ini_options]
addopts = "--cov={{cookiecutter.project_slug.lower()}} --cov-report=html --cov-fail-under=90 --doctest-modules --doctest-glob='*.rst' --ignore=core --ignore=docs --ignore=venv --ignore=.venv --ignore=.env"

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
extend-exclude = '''
(
  ^/core/*
  ^/docs/*
  ^.venv/*
  ^.env/
)
'''

[tool.taskipy.tasks]
build-all = "python manage.py build --all"
build-fastapi = "python manage.py fastapi"
build-flutter = "python manage.py flutter"
build-flutter-mobile = "python manage.py flutter_mobile"
rebuild-flutter-mobile = "rm -rf ../../FlutterMobile/{{cookiecutter.project_slug.lower()}} && python manage.py flutter_mobile --all && code ../../FlutterMobile/{{cookiecutter.project_slug.lower()}}/. "
build-flutter-web = "python manage.py flutter_web"
rebuild-flutter-web = "rm -rf ../../FlutterWeb/{{cookiecutter.project_slug.lower()}} && python manage.py flutter_web --all && code ../../FlutterWeb/{{cookiecutter.project_slug.lower()}}/. "
build-force = "python manage.py build --all --force"
core-upgrade = "python manage.py core --upgrade"
core-version = "python manage.py core --version"
coverage = "coverage html"
docs = "mkdocs serve"
lint = "black --diff --color . && isort --check-only --diff ."
mgt = "python manage.py migrate"
mkm = "python manage.py makemigrations"
post-test = "coverage html"
pre-test = "task lint"
run = "python manage.py runserver"
runserver = "python manage.py runserver"
shell = "python manage.py shell"
startapp = "python manage.py startapp"
test = "pytest -s -x --cov={{cookiecutter.project_slug.lower()}} -vv"
