# Generated by Django 3.0.5 on 2023-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parameterforbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='current_data',
            field=models.TextField(help_text='data at the time of the change'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='fields_change',
            field=models.TextField(blank=True, help_text='Form_principal or Model fields that have been modified', null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='previous_data_change',
            field=models.TextField(help_text='before the time of the change'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user_change',
            field=models.TextField(help_text='user who changed the data', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user_groups_change',
            field=models.TextField(help_text='groups at the time of change', verbose_name='user groups'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user_permissions_change',
            field=models.TextField(help_text='permissions at the time of change', verbose_name='user permissions'),
        ),
    ]
