# Generated by Django 3.0.5 on 2023-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230104_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
