# Generated by Django 3.0.5 on 2023-01-03 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterForBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomeProjeto', models.TextField(blank=True, default='', null=True)),
                ('tituloProjeto', models.TextField(blank=True, default='', null=True)),
                ('descricaoProjeto', models.TextField(blank=True, default='', null=True)),
                ('iconeProjeto', models.TextField(blank=True, default='', null=True)),
                ('login_redirect_url', models.CharField(blank=True, default='/core/', max_length=250, null=True)),
                ('login_url', models.CharField(blank=True, default='/core/login/', max_length=250, null=True)),
                ('logout_redirect_url', models.CharField(blank=True, default='/core/login/', max_length=250, null=True)),
                ('url_integracao', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('audit_enable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parametro para o Core',
                'verbose_name_plural': 'Parametros para o Core',
            },
        ),
    ]
