# Generated by Django 3.0.5 on 2023-01-04 12:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='current_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='data at the time of the change'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='fields_change',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Form_principal or Model fields that have been modified', null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='previous_data_change',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='before the time of the change'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user_change',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='user who changed the data', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user_groups_change',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='groups at the time of change', verbose_name='user groups'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user_permissions_change',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='permissions at the time of change', verbose_name='user permissions'),
        ),
    ]
