# Generated by Django 3.2.19 on 2023-05-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendente', to='usuario.usuario', verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='usuario.usuario', verbose_name='Usuário'),
        ),
    ]
