[tool.taskipy.settings]
user_vars = true

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
max-line-length = 88
line-length = 88
ignore = "E203, W503"
extend-exclude = '''
(
  ^/docs/*
  ^.venv/*
  ^.env/
)
'''

[tool.taskipy.tasks]
run = "python -m uvicorn main:app --reload"
